# Generated by Django 2.2.1 on 2019-06-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=32, unique=True)),
                ('stream_url', models.CharField(max_length=1000)),
                ('access_info', models.CharField(max_length=45)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'res_camera',
            },
        ),
        migrations.CreateModel(
            name='CameraGroup',
            fields=[
                ('camera_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_group_name', models.CharField(max_length=255)),
                ('camera_group_color', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'res_camera_groups',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('function_id', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fccm_function',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_code', models.CharField(max_length=255)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'res_people',
            },
        ),
        migrations.CreateModel(
            name='PeopleGroup',
            fields=[
                ('people_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('people_group_code', models.CharField(max_length=50)),
                ('people_group_name', models.CharField(max_length=255)),
                ('people_group_color', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'res_people_groups',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_id', models.AutoField(primary_key=True, serialize=False)),
                ('process_name', models.CharField(max_length=255)),
                ('process_token', models.CharField(max_length=100, null=True)),
                ('process_config', models.CharField(max_length=2083, null=True)),
                ('process_status', models.IntegerField()),
                ('people_group_id', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('camera_id', models.ForeignKey(db_column='camera_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.Camera')),
            ],
            options={
                'db_table': 'process',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('owner_user_id', models.IntegerField()),
                ('secret_key', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fccm_project',
            },
        ),
        migrations.CreateModel(
            name='XrefProcessPeopleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_group_id', models.ForeignKey(db_column='people_group_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.PeopleGroup')),
                ('process_id', models.ForeignKey(db_column='process_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.Process')),
            ],
            options={
                'db_table': 'xref_process_people_group',
            },
        ),
        migrations.CreateModel(
            name='XrefPeopleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_group_id', models.ForeignKey(db_column='people_group_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.PeopleGroup')),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.People')),
            ],
            options={
                'db_table': 'res_people_people_groups_xrefs',
            },
        ),
        migrations.CreateModel(
            name='XrefCameraGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_group_id', models.ForeignKey(db_column='camera_group_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.CameraGroup')),
                ('camera_id', models.ForeignKey(db_column='camera_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.Camera')),
            ],
            options={
                'db_table': 'res_camera_camera_groups_xrefs',
            },
        ),
        migrations.CreateModel(
            name='ResPeopleImage',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_file', models.CharField(max_length=2083, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.People')),
            ],
            options={
                'db_table': 'res_people_recognition_assets_image_v2',
            },
        ),
        migrations.AddField(
            model_name='process',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.Project'),
        ),
        migrations.AddField(
            model_name='peoplegroup',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.Project'),
        ),
        migrations.AddField(
            model_name='people',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.Project'),
        ),
        migrations.AddField(
            model_name='cameragroup',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.Project'),
        ),
        migrations.AddField(
            model_name='camera',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.Project'),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('api_key_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=500)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('function_id', models.ForeignKey(db_column='function_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.Function')),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='fcloudserver.Project')),
            ],
            options={
                'db_table': 'fcct_api_key',
            },
        ),
    ]
