# Generated by Django 2.2.1 on 2019-06-19 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fccm_user',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_role_description', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'fccm_user_role',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('user_token_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'fccm_user_token',
            },
        ),
        migrations.CreateModel(
            name='XrefAvatarUser',
            fields=[
                ('avatar_id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar_file', models.CharField(max_length=2083, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fccm_user_avatar',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fccm_profile',
            },
        ),
    ]
